### ISSUE TITLE
Docker functionality for the front-end

### ISSUE THREAD

**Issue by eskildsvennungsen** [eskildsvennungsen/metern#10]
Create a dockerfile in the client folder and update the docker-compose.yaml

**Comment by IntrntSrfr** [comment]
What should the image be doing? Should it be a dev-image with live updates as you make changes, or a production image that contains the final build?

**Comment by eskildsvennungsen** [comment]
Foreløpig brukes det et produksjons image, vet ikke helt hva som er best. Men det funker enn så lenge.
